### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by philipp-schmidt** [wemaintain/auto-relay#26]
When installing with yarn, I get a bunch of unmet peer dependencies.
I had to install graphql-relay, @types/graphql-relay and typedi to get rid of them.

Still I'm left with the following:

`warning " > @auto-relay/typeorm@0.12.6" has incorrect peer dependency "auto-relay@^0.6.1".`

Is this up to date?

Awesome lib btw, exactly what I was searching for!

**Comment by Superd22** [comment]
Hey, thanks for the kind comment!

Those are definitely mistakes on our part, thanks for spotting them. I'll address them for next version :)

**Comment by pulzarraider** [comment]
This issue is causing npm install error:

```
> npm install @auto-relay/typeorm
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: notification@1.0.0
npm ERR! Found: auto-relay@0.12.9
npm ERR! node_modules/auto-relay
npm ERR!   auto-relay@"^0.12.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer auto-relay@"^0.6.1" from @auto-relay/typeorm@0.12.9
npm ERR! node_modules/@auto-relay/typeorm
npm ERR!   @auto-relay/typeorm@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I have fixed it with `--force`. Can you please fix the issue?
