### ISSUE TITLE
@RelayedQuery() doesn't work on Nestjs 7 version. 

### ISSUE THREAD

**Issue by ZhoraGrig** [wemaintain/auto-relay#31]
I don't get any errors or anything, but my @RelayedQuery decorated function don't show up and doesn't generate types and query.

**Comment by kodeine** [comment]
how are you using it? code > words :)

**Comment by kodeine** [comment]
agreed. it doesnt work on nest 7

**Comment by ZhoraGrig** [comment]
Hi @Superd22 can you fix it ?

**Comment by Superd22** [comment]
Hey @ZhoraGrig @kodeine , this is a dupe of #23 ;)
