### ISSUE TITLE
Compatibility with TypeGraphQL 1.x

### ISSUE THREAD

**Issue by emielvanliere** [wemaintain/auto-relay#42]
First of all, thanks for creating this library.

Unfortunately it does not seem to work with TypeGrapQL 1.1.0. I did notice a `tqvl1` branch https://github.com/wemaintain/auto-relay/tree/tgqlv1 that uses typegraphql 1.0.0 but that appears to be very much a work in progress. Is still still being worked on?

Thanks!

**Comment by Superd22** [comment]
Hey @emielvanliere , we're currently using `0.13.0-alpha.0` in production with TypeGraphQL 1.0.0.
0.13.0 will get out of alpha in a couple weeks as soon as we get around to it. :)

**Comment by emielvanliere** [comment]
Sounds great, I'll give it a go!

**Comment by emielvanliere** [comment]
Unfortunately I can't seem to get auto-relay to generate the paginate sdl for connections. I've created a very simple example repo at https://github.com/emielvanliere/auto-relay-example that generates the following SDL: 

```
directive @specifiedBy(url: String!) on SCALAR
type Query {
  users: [User!]!
}

type User {
  id: Float!
  name: String!
}
```

As you can see there are no fields for the `recipes` connection. I would expect it to to create something similar to the example in the auto-relay readme. Am I doing something wrong here?

**Comment by Superd22** [comment]
@emielvanliere as specified in the docs, https://github.com/emielvanliere/auto-relay-example/blob/master/src/resolvers/UserResolver.ts#L9 you're supposed to use `@RelayedQuery` https://superd001.gitbook.io/autorelay/pagination-1/relayd-query

Obviously we want users to still be able to return arrays if they so desire :)

**Comment by emielvanliere** [comment]
Turns out that I had to add [`createConnection`](https://github.com/emielvanliere/auto-relay-example/blob/3bb7762abe144002de240295a0124c5edff7fa27/src/app/app.ts#L11) to make it work. 

Thanks for the feedback!

**Comment by emielvanliere** [comment]
FYI: the reason for it not working on our codebase was that we initialised our graphql schema synchronously with: `TypeGraphQL.buildSchema.buildSchemaSync(..)`. After changing that to the async version `TypeGraphQL.buildSchema(..)` auto-relay connections showed up in the SDL.
