### ISSUE TITLE
Having issues with @RelayedQuery()

### ISSUE THREAD

**Issue by mattpetters** [wemaintain/auto-relay#45]
Initializing the library like in the docs and adding the following query (adapted from the docs) results in no query showing up on my schema.

```typescript
 @RelayedQuery(() => Product)
  async bestSellers(
    @RelayLimitOffset() {limit, offset}: RelayLimitOffsetArgs,
    @Arg("type", ()=>ProductType) productType: ProductType
  ): Promise<[Product[], number]> {
    const productRepository = getRepository(Product);
    return await productRepository.findAndCount({ 
      where: { 
        type: productType
      },
      skip: offset,
      take: limit
    })
  }

```
 
Below are my typeorm/type-graphql versions from `package.json`

```json
    "type-graphql": "^1.0.0-rc.3",
    "typeorm": "^0.2.25"
```

Is this library still maintained and intended to be compatible with modern versions of typegraphql (> 1.0.0)?

**Comment by Superd22** [comment]
Heya!

Can you try `0.13.0-alpha.0` ?
We're using it in prod with tgql 1.1.0

(We'll release it as 0.13.0 as soon as we get around to it)

**Comment by mattpetters** [comment]
Sure! Will do, I saw that tag but wasn't sure the state given the `-alpha`ness ;) I'll let you know how it goes.

**Comment by mattpetters** [comment]
Still not working for me but it could be due to using a string path for my resolvers array (`"./**/*.resolvers.{ts,js}"`) instead of populating each resolver in my schema initialization. I believe I saw that that was still a bug in another issue.
