### ISSUE TITLE
refetchable directive not working

### ISSUE THREAD

**Issue by MoSattler** [wemaintain/auto-relay#74]
When trying to use the refetchable on a node generated by auto-relay, relay gives the following error
```
ERROR:
- Invalid use of @refetchable on fragment 'MenuItemList_menuItems', only supported are fragments on:
   - the Viewer type
   - the Query type
   - the Node interface or types implementing the Node interface
   - @fetchable types
  
  Source: src/Restaurant/components/MenuItemList/index.tsx (2:7)
  1: 
  2:       fragment MenuItemList_menuItems on MenuItem
           ^
  3:       @refetchable(queryName: "MenuItemListRefetchQuery")
  ```
  fragment:
  ```gql
 fragment MenuItemList_menuItems on MenuItem
    @refetchable(queryName: "MenuItemListRefetchQuery")
    @relay(plural: true) 
    {
      id
    }
  ```
  
  The query is this one:
  ```gql
  query MenuItemQuery($id: ID!) {
    menuItem(id: $id) {
      reviews {
        edges {
          ...ReviewList_reviews
        }
      }
    }
  }
  ```
  
  Looking at the generated schema, it looks like that with auto-relay does not generate nodes that implement the Node interface, [as the relay spec requires](https://relay.dev/docs/guides/graphql-server-specification/#schema).

**Comment by MoSattler** [comment]
I was able to solve it by defining the interfaces myself:
https://typegraphql.com/docs/interfaces.html#implementing-other-interfaces

**Comment by Superd22** [comment]
Indeed.

There used to be issues with sharing an interface across multiple schemas when using federation when this lib was first designed, so we went the route of not requiring classes to implements Node.

We should probably add it as a best practice to the docs though.
