### ISSUE TITLE
How to make RelayLimitOffset work with non-numerical IDs?

### ISSUE THREAD

**Issue by MoSattler** [wemaintain/auto-relay#81]
It seems like the assumption is that numerical IDs are used, looking at [this code](https://github.com/wemaintain/auto-relay/blob/619613545cd3940a8ac4c0835b80facc080cad20/packages/core/src/services/limit-offset-paging.service.ts#L81-L88).
How can one make this work with other forms of IDs, e.g. TypeORM `@PrimaryGeneratedColumn("uuid")`?

A first step for me would be getting just the normal ID and figure out the offset myself - but right now it seems that auto-relay is parsing my UUID to numbers with `parseInt`, which doesn't produce anything useful.

**Comment by MoSattler** [comment]
Hi @Superd22, it would already be super helpful to be able to deactivate auto-relay's pagination (as it is not working right now for me), so I can add my own relay compliant pagination, working for my use case. 

Right now, I cannot do this, as auto-relay starts messing with my things as soon as `after` is set on a query.

**Comment by Superd22** [comment]
Hey @MoSattler, sorry for the long answer time.

We've been using auto-relay in production with non-integer ID for quite some time (including uuids) using **forward** only pagination. (ie: not using `last`/`before`).

What exactly seems to be the problem for you ?

**Comment by MoSattler** [comment]
hey @Superd22, I stopped using auto-relay due to this problem, and I don't quite remember what the issue was.
